-- Run this in Supabase SQL Editor.
-- Then create a Storage bucket named "chat-media".
-- IMPORTANT: this starter uses public media URLs for simplicity.
-- For a private production app, make the bucket private and use signed URLs.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references auth.users(id) on delete cascade,
  user_b uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_a,user_b),
  check(user_a <> user_b)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  media_url text,
  media_type text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

create or replace function public.is_conversation_member(cid uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists(
    select 1 from public.conversations c
    where c.id=cid and (c.user_a=auth.uid() or c.user_b=auth.uid())
  );
$$;

create policy "profiles visible to signed in users"
on public.profiles for select to authenticated using (true);

create policy "users can read their conversations"
on public.conversations for select to authenticated
using (auth.uid()=user_a or auth.uid()=user_b);

create policy "users can insert conversations"
on public.conversations for insert to authenticated
with check (auth.uid()=user_a or auth.uid()=user_b);

create policy "members read messages"
on public.messages for select to authenticated
using (public.is_conversation_member(conversation_id));

create policy "members send messages"
on public.messages for insert to authenticated
with check (
  sender_id=auth.uid()
  and public.is_conversation_member(conversation_id)
);

create or replace function public.find_user_by_email(target_email text)
returns table(id uuid,email text)
language sql security definer set search_path=public
as $$
  select p.id,p.email from public.profiles p
  where lower(p.email)=lower(target_email)
  limit 1;
$$;

grant execute on function public.find_user_by_email(text) to authenticated;

create or replace function public.get_or_create_conversation(other_user_id uuid)
returns uuid
language plpgsql security definer set search_path=public
as $$
declare
  me uuid := auth.uid();
  result_id uuid;
  a uuid;
  b uuid;
begin
  if me is null then raise exception 'Not authenticated'; end if;
  if me=other_user_id then raise exception 'Cannot chat with yourself'; end if;

  a := least(me,other_user_id);
  b := greatest(me,other_user_id);

  select id into result_id from public.conversations
  where user_a=a and user_b=b;

  if result_id is null then
    insert into public.conversations(user_a,user_b)
    values(a,b)
    returning id into result_id;
  end if;
  return result_id;
end;
$$;

grant execute on function public.get_or_create_conversation(uuid) to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,email) values(new.id,new.email)
  on conflict(id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable realtime for messages.
alter publication supabase_realtime add table public.messages;
